CREATE TABLE STUDENTREC 
( 
ID int(5),
Name VARCHAR(25) NOT NULL,
Age int
 );
INSERT INTO STUDENTREC VALUES(1,'Vinodhini',25);
INSERT INTO STUDENTREC VALUES(2,'Bhanu',27);
INSERT INTO STUDENTREC VALUES(3,'Kaushik',23);
INSERT INTO STUDENTREC VALUES(4,'Praveen',25);
INSERT INTO STUDENTREC VALUES(5,'Kamal',22);
INSERT INTO STUDENTREC VALUES(6,'Malini',24);
INSERT INTO STUDENTREC VALUES(7,'Ramesh',32);
SELECT * FROM STUDENTREC WHERE AGE='32' OR AGE='22';