CREATE TABLE EMPLOYEE 
( 
ID int(5) PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(25) NOT NULL,
Age int
 );
INSERT INTO EMPLOYEE(Name,age) VALUES('Vinodhini',25);
INSERT INTO EMPLOYEE(Name,age) VALUES('Bhanu',27);
INSERT INTO EMPLOYEE(Name,age) VALUES('Kaushik',23);
INSERT INTO EMPLOYEE(Name,age) VALUES('Praveen',25);
INSERT INTO EMPLOYEE(Name,age) VALUES('Kamal',22);
INSERT INTO EMPLOYEE(Name,age) VALUES('Malini',24);
INSERT INTO EMPLOYEE(Name,age) VALUES('Ramesh',32);

