INSERT INTO RSTUDENT VALUES('SAI','RAM','Mr','M','CHENNAI','TN','INDIA',21,'SAMOSA','COD');
INSERT INTO RSTUDENT VALUES('HARI','RAJ','Mr','M','HYDERABAD','AP','INDIA',21,'PURI','JAX');
INSERT INTO RSTUDENT VALUES('SAI','RAM','Mr','M','CHENNAI','TN','INDIA',21,'SAMOSA','COD');
SELECT * from RSTUDENT;
SELECT COUNT(*) FROM RSTUDENT;
SELECT DISTINCT(FIRST_NAME) FROM RSTUDENT;